### ISSUE TITLE
GenericError: Generic API error happened.

### ISSUE THREAD

**Issue by leekuanyewsgp** [Gimenz/tiktok-downloader#17]
GenericError: Generic API error happened.
    at UserRepository.<anonymous> (E:\Automation\TikTok\tiktok-downloader-Gimenz\tiktok-downloader\node_modules\tiktok-private-api\build\repositories\user.repository.js:116:19)
    at Generator.next (<anonymous>)
    at fulfilled (E:\Automation\TikTok\tiktok-downloader-Gimenz\tiktok-downloader\node_modules\tiktok-private-api\build\repositories\user.repository.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by leekuanyewsgp** [comment]
<img width="1243" alt="Screenshot 2024-06-15 182613" src="https://github.com/Gimenz/tiktok-downloader/assets/158373362/f64b9087-699c-4666-8fa1-8f562dff849a">

**Comment by Gimenz** [comment]
i'm sorry i didnt know for this, i use a module from https://github.com/atharahmed/tiktok-private-api
and it worked for me
![image](https://github.com/Gimenz/tiktok-downloader/assets/23699593/e6bb1c5f-23e2-4e0c-b4ca-7c15d6ca2f7c)
